info:
  application:
    name: top-king
    author: Mike Dunn
    version: '@project.version@'

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

spring:
  datasource:
    driver-class:
      name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: medunn626@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  sql:
    init:
      mode: always

twilio:
  account_sid: ACbe15b475c5f9654a7a50fcf4db1c16cc
  auth_token: ${TWILIO_TOKEN}
  trial_number: 18334925940

