spring:
  datasource:
    url: jdbc:mysql://localhost:3306/topking
    username: root
    password: letmein
    name: top-king
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: medunn626@gmail.com
    password: mijfgcdgpqdsmiew
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true