info:
  application:
    name: top-king
    author: Mike Dunn
    version: '@project.version@'

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

spring:
  datasource:
    driver-class:
      name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_EMAIL}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 3000MB
      max-request-size: 3000MB
  sql:
    init:
      mode: always

private_key_id: ${DRIVE_PRIVATE_KEY_ID}
client_email: ${DRIVE_CLIENT_EMAIL}
client_id: ${DRIVE_CLIENT_ID}

backup_private_key_id: ${DRIVE_BACKUP_PRIVATE_KEY_ID}
backup_client_email: ${DRIVE_BACKUP_CLIENT_EMAIL}
backup_client_id: ${DRIVE_BACKUP_CLIENT_ID}

