spring:
  datasource:
    url: jdbc:mysql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: medunn626@gmail.com
    password: ${GMAIL_PASSWORD}
    properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true